name: luna
favicon: null
layout_spectrum: 0.5020244102925062
typography_spectrum: 0.5759921960998327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1827586458530277
  lightness: 0.6338879198301584
  saturation: 0.9514424151275307
  rhythmicContrast: 0.680419844109565
purpose: []
